# Generated by Django 3.1.2 on 2020-10-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Physical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='product',
            new_name='name',
        ),
    ]
