# Generated by Django 3.1.2 on 2020-10-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Physical', '0002_auto_20201014_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='name',
            new_name='product',
        ),
    ]
